### ISSUE TITLE
Source map support breaks when CSON is required

### ISSUE THREAD

**Issue by lzrski** [bevry/cson#45]
Hi and thanks for this stuff.

Consider following snippet.

```coffee-script
require 'source-map-support'
  .install()

e = new Error "There's an error in your coffee."

console.trace e

require "cson"

console.trace e

```

Running:

```
coffee -cm test.coffee
node test.js
```

Gives me:

```
Trace: [Error: There's an error in your coffee.]
    at Object.<anonymous> (/home/tadeusz/Projects/dredd/test.coffee:5:9)
    at Object.<anonymous> (/home/tadeusz/Projects/dredd/test.coffee:1:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Trace: [Error: There's an error in your coffee.]
  at Object.<anonymous> (/home/tadeusz/Projects/dredd/test.js:13:11)
  at Object.<anonymous> (/home/tadeusz/Projects/dredd/test.js:15:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

The second trace ignores source-map and refers to compiled `test.js` file.

Not sure if it's a problem with CSON or source-map-support. Anyway this doesn't happen with [cson-safe](https://www.npmjs.org/package/cson-safe).

**Comment by balupton** [comment]
Possibly fixed in v2.
