### ISSUE TITLE
biscotto is no longer a thing

### ISSUE THREAD

**Issue by balupton** [bevry/cson#76]
```
"meta": "npm run meta:biscotto && npm run meta:projectz",
"meta:biscotto": "biscotto -n $npm_package_title --title \"$npm_package_title API Documentation\" -r README.md -o ./docs ./src - ./LICENSE.md ./HISTORY.md",    
```

produces:

```
$ npm run meta:biscotto

> cson@4.0.0 meta:biscotto /Users/balupton/Projects/active/cson
> biscotto -n $npm_package_title --title "$npm_package_title API Documentation" -r README.md -o ./docs ./src - ./LICENSE.md ./HISTORY.md

/Users/balupton/Projects/active/cson/node_modules/biscotto/src/biscotto.coffee:73
            extraUsage = defaults.extras.length === 0 ? '' : "- " + (defaults.extras.join(' '));
                                                                                     ^

TypeError: defaults.extras.join is not a function
  at /Users/balupton/Projects/active/cson/node_modules/biscotto/src/biscotto.coffee:86:89
  at /Users/balupton/Projects/active/cson/node_modules/async/dist/async.js:3853:9
  at /Users/balupton/Projects/active/cson/node_modules/async/dist/async.js:484:16
  at iterateeCallback (/Users/balupton/Projects/active/cson/node_modules/async/dist/async.js:1013:24)
  at /Users/balupton/Projects/active/cson/node_modules/async/dist/async.js:988:16
  at /Users/balupton/Projects/active/cson/node_modules/async/dist/async.js:3850:13
  at apply (/Users/balupton/Projects/active/cson/node_modules/async/dist/async.js:41:25)
  at /Users/balupton/Projects/active/cson/node_modules/async/dist/async.js:76:12
  at /Users/balupton/Projects/active/cson/node_modules/biscotto/src/biscotto.coffee:421:7
  at ChildProcess.exithandler (child_process.js:197:7)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:877:16)
  at Socket.<anonymous> (internal/child_process.js:334:11)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**Comment by balupton** [comment]
DocPad uses yuidoc for its documentation which still works. We can also move CSON over to JavaScript like the rest of our projects, however considering this a CoffeeScript project, keeping it in CoffeeScript would make sense.

The question would be weather YUIdoc supports markdown generation like we have in our current README, otherwise perhaps we may need to get rid of the readme docs and just link to the generated hosted docs.

**Comment by balupton** [comment]
luckily `"biscotto": "emmenko/biscotto#v2.4.0"` fixes this
